

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    password: ou123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.84.101
    password: 123456
    port: 6379
  session:
    store-type: redis
  http:
    multipart:
      max-file-size: 512000
      file-size-threshold: 512000


mybatis:
  type-aliases-package: com.ou.**.pojo
  mapper-locations:
    - classpath*:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    cache-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework: info


com:
  ou:
    allowedOrigins:
      - http://localhost:9001
      - http://localhost:9002
      - http://127.0.0.1:9001
      - http://127.0.0.1:9002
    custom:
      providerId: custom
      appid: seehope
      appsecret: ou123456
    staticPermitUrl:
      - /css/*
      - /fonts/*
      - /images/*
    formLogin:
      loginPage: /index.html
      LoginProcessingUrl: /authentication/form
      usernameParam: username
      passwordParam: password
      loginType: JSON
    imgFileUri:
      D:\imageTest\foodieImage
    imgFileUrl:
      http://localhost:8081/foodieImage
#security:
#  oauth2:
#    client:
#      client-id: seehope
#      client-secret: ou123456
server:
  port: 8081
  session:
    timeout: 7200

