

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db14?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    password: ou123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.84.101
    password: 123456
    port: 6379
  session:
    store-type: redis
mybatis:
  type-aliases-package: com.ou.**.entity
  mapper-locations:
    - classpath*:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    cache-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework: info


com:
  ou:
    custom:
      providerId: custom
      appid: seehope
      appsecret: ou123456
    staticPermitUrl:
      - /css/*
      - /fonts/*
      - /images/*
    formLogin:
      loginPage: /index.html
      LoginProcessingUrl: /authentication/form
      usernameParam: username
      passwordParam: password
      loginType: JSON
security:
  oauth2:
    client:
      client-id: seehope
      client-secret: ou123456
server:
  port: 8081
  session:
    timeout: 7200

