spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    password: ou123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: 123456
    port: 6379
    host: 192.168.84.101
    database: 0
    timeout: 0
  session:
    store-type: redis

mybatis:
  type-aliases-package: com.ou.**.pojo
  mapper-locations:
    - classpath*:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    cache-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.springframework: info


com:
  ou:
    allowedOrigins:
      - http://localhost:9001
      - http://localhost:9002
      - http://127.0.0.1:9001
      - http://127.0.0.1:9002
    oauth2:
      storeType: redis
      client[0]:
        clientId: seehope
        clientSecret: ou123456
        autoApprove: all
        refreshTokenValiditySeconds: 604800
        accessTokenValiditySeconds: 7200
        authorities:
          - client
        resourceIds:
          - client
        authorizedGrantTypes:
          - refresh_token
          - authorization_code
          - custom
        redirectUris:
          - http://localhost:8081/social/custom
        scopes:
          - getUserInfo
          - all


    staticPermitUrl:
      - /css/*
      - /fonts/*
      - /images/*
    formLogin:
      loginPage: /index.html
      LoginProcessingUrl: /authentication/form
      usernameParam: username
      passwordParam: password
      loginType: JSON
security:
  oauth2:
    client:
      client-id: seehope
      client-secret: ou123456
server:
  session:
    timeout: 7200
